/** \file
 *  This C header file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : src/grammar/V4.g
 *     -                            On : 2024-12-26 10:16:00
 *     -                for the parser : V4ParserParser
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The parser 
V4Parser

has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 *
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef pV4Parser, which is returned from a call to V4ParserNew().
 *
 * The methods in pV4Parser are  as follows:
 *
 *  - 
 V4Parser_source_return
      pV4Parser->source(pV4Parser)
 *  - 
 V4Parser_sourceItem_return
      pV4Parser->sourceItem(pV4Parser)
 *  - 
 V4Parser_funcDef_return
      pV4Parser->funcDef(pV4Parser)
 *  - 
 V4Parser_funcSignature_return
      pV4Parser->funcSignature(pV4Parser)
 *  - 
 V4Parser_arg_return
      pV4Parser->arg(pV4Parser)
 *  - 
 V4Parser_list_arg_return
      pV4Parser->list_arg(pV4Parser)
 *  - 
 V4Parser_typeRef_return
      pV4Parser->typeRef(pV4Parser)
 *  - 
 V4Parser_builtin_return
      pV4Parser->builtin(pV4Parser)
 *  - 
 V4Parser_custom_return
      pV4Parser->custom(pV4Parser)
 *  - 
 V4Parser_arrayType_return
      pV4Parser->arrayType(pV4Parser)
 *  - 
 V4Parser_arraySuffix_return
      pV4Parser->arraySuffix(pV4Parser)
 *  - 
 V4Parser_baseType_return
      pV4Parser->baseType(pV4Parser)
 *  - 
 V4Parser_statement_return
      pV4Parser->statement(pV4Parser)
 *  - 
 V4Parser_variableDefinition_return
      pV4Parser->variableDefinition(pV4Parser)
 *  - 
 V4Parser_variableDeclaration_return
      pV4Parser->variableDeclaration(pV4Parser)
 *  - 
 V4Parser_ifStmt_return
      pV4Parser->ifStmt(pV4Parser)
 *  - 
 V4Parser_elsePart_return
      pV4Parser->elsePart(pV4Parser)
 *  - 
 V4Parser_loopStmt_return
      pV4Parser->loopStmt(pV4Parser)
 *  - 
 V4Parser_repeatStmt_return
      pV4Parser->repeatStmt(pV4Parser)
 *  - 
 V4Parser_repeatSuffix_return
      pV4Parser->repeatSuffix(pV4Parser)
 *  - 
 V4Parser_breakStmt_return
      pV4Parser->breakStmt(pV4Parser)
 *  - 
 V4Parser_expressionStmt_return
      pV4Parser->expressionStmt(pV4Parser)
 *  - 
 V4Parser_blockStmt_return
      pV4Parser->blockStmt(pV4Parser)
 *  - 
 V4Parser_blockStart_return
      pV4Parser->blockStart(pV4Parser)
 *  - 
 V4Parser_blockEnd_return
      pV4Parser->blockEnd(pV4Parser)
 *  - 
 V4Parser_statementList_return
      pV4Parser->statementList(pV4Parser)
 *  - 
 V4Parser_assignmentStmt_return
      pV4Parser->assignmentStmt(pV4Parser)
 *  - 
 V4Parser_returnStmt_return
      pV4Parser->returnStmt(pV4Parser)
 *  - 
 V4Parser_expr_return
      pV4Parser->expr(pV4Parser)
 *  - 
 V4Parser_binaryExpr_return
      pV4Parser->binaryExpr(pV4Parser)
 *  - 
 V4Parser_unaryExpr_return
      pV4Parser->unaryExpr(pV4Parser)
 *  - 
 V4Parser_call_return
      pV4Parser->call(pV4Parser)
 *  - 
 V4Parser_slice_return
      pV4Parser->slice(pV4Parser)
 *  - 
 V4Parser_braces_return
      pV4Parser->braces(pV4Parser)
 *  - 
 V4Parser_place_return
      pV4Parser->place(pV4Parser)
 *  - 
 V4Parser_bool_return
      pV4Parser->bool(pV4Parser)
 *  - 
 V4Parser_literal_return
      pV4Parser->literal(pV4Parser)
 *  - 
 V4Parser_ranges_return
      pV4Parser->ranges(pV4Parser)
 *  - 
 V4Parser_list_expr_return
      pV4Parser->list_expr(pV4Parser)
 *  - 
 V4Parser_list_range_return
      pV4Parser->list_range(pV4Parser)
 *  - 
 V4Parser_binOp_return
      pV4Parser->binOp(pV4Parser)
 *  - 
 V4Parser_unOp_return
      pV4Parser->unOp(pV4Parser)
 * 
 * 
 * 
 * 
 * 
 * 
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_V4Parser_H
#define _V4Parser_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */

#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct V4Parser_Ctx_struct V4Parser, * pV4Parser;



#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif

/* ========================
 * BACKTRACKING IS ENABLED
 * ========================
 */

typedef struct V4Parser_source_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    V4Parser_source_return;



typedef struct V4Parser_sourceItem_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    V4Parser_sourceItem_return;



typedef struct V4Parser_funcDef_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    V4Parser_funcDef_return;



typedef struct V4Parser_funcSignature_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    V4Parser_funcSignature_return;



typedef struct V4Parser_arg_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    V4Parser_arg_return;



typedef struct V4Parser_list_arg_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    V4Parser_list_arg_return;



typedef struct V4Parser_typeRef_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    V4Parser_typeRef_return;



typedef struct V4Parser_builtin_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    V4Parser_builtin_return;



typedef struct V4Parser_custom_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    V4Parser_custom_return;



typedef struct V4Parser_arrayType_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    V4Parser_arrayType_return;



typedef struct V4Parser_arraySuffix_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    V4Parser_arraySuffix_return;



typedef struct V4Parser_baseType_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    V4Parser_baseType_return;



typedef struct V4Parser_statement_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    V4Parser_statement_return;



typedef struct V4Parser_variableDefinition_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    V4Parser_variableDefinition_return;



typedef struct V4Parser_variableDeclaration_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    V4Parser_variableDeclaration_return;



typedef struct V4Parser_ifStmt_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    V4Parser_ifStmt_return;



typedef struct V4Parser_elsePart_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    V4Parser_elsePart_return;



typedef struct V4Parser_loopStmt_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    V4Parser_loopStmt_return;



typedef struct V4Parser_repeatStmt_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    V4Parser_repeatStmt_return;



typedef struct V4Parser_repeatSuffix_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    V4Parser_repeatSuffix_return;



typedef struct V4Parser_breakStmt_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    V4Parser_breakStmt_return;



typedef struct V4Parser_expressionStmt_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    V4Parser_expressionStmt_return;



typedef struct V4Parser_blockStmt_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    V4Parser_blockStmt_return;



typedef struct V4Parser_blockStart_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    V4Parser_blockStart_return;



typedef struct V4Parser_blockEnd_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    V4Parser_blockEnd_return;



typedef struct V4Parser_statementList_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    V4Parser_statementList_return;



typedef struct V4Parser_assignmentStmt_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    V4Parser_assignmentStmt_return;



typedef struct V4Parser_returnStmt_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    V4Parser_returnStmt_return;



typedef struct V4Parser_expr_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    V4Parser_expr_return;



typedef struct V4Parser_binaryExpr_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    V4Parser_binaryExpr_return;



typedef struct V4Parser_unaryExpr_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    V4Parser_unaryExpr_return;



typedef struct V4Parser_call_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    V4Parser_call_return;



typedef struct V4Parser_slice_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    V4Parser_slice_return;



typedef struct V4Parser_braces_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    V4Parser_braces_return;



typedef struct V4Parser_place_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    V4Parser_place_return;



typedef struct V4Parser_bool_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    V4Parser_bool_return;



typedef struct V4Parser_literal_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    V4Parser_literal_return;



typedef struct V4Parser_ranges_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    V4Parser_ranges_return;



typedef struct V4Parser_list_expr_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    V4Parser_list_expr_return;



typedef struct V4Parser_list_range_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    V4Parser_list_range_return;



typedef struct V4Parser_binOp_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    V4Parser_binOp_return;



typedef struct V4Parser_unOp_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    V4Parser_unOp_return;




/** Context tracking structure for 
V4Parser

 */
struct V4Parser_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_PARSER   pParser;

     V4Parser_source_return
     (*source)	(struct V4Parser_Ctx_struct * ctx);

     V4Parser_sourceItem_return
     (*sourceItem)	(struct V4Parser_Ctx_struct * ctx);

     V4Parser_funcDef_return
     (*funcDef)	(struct V4Parser_Ctx_struct * ctx);

     V4Parser_funcSignature_return
     (*funcSignature)	(struct V4Parser_Ctx_struct * ctx);

     V4Parser_arg_return
     (*arg)	(struct V4Parser_Ctx_struct * ctx);

     V4Parser_list_arg_return
     (*list_arg)	(struct V4Parser_Ctx_struct * ctx);

     V4Parser_typeRef_return
     (*typeRef)	(struct V4Parser_Ctx_struct * ctx);

     V4Parser_builtin_return
     (*builtin)	(struct V4Parser_Ctx_struct * ctx);

     V4Parser_custom_return
     (*custom)	(struct V4Parser_Ctx_struct * ctx);

     V4Parser_arrayType_return
     (*arrayType)	(struct V4Parser_Ctx_struct * ctx);

     V4Parser_arraySuffix_return
     (*arraySuffix)	(struct V4Parser_Ctx_struct * ctx);

     V4Parser_baseType_return
     (*baseType)	(struct V4Parser_Ctx_struct * ctx);

     V4Parser_statement_return
     (*statement)	(struct V4Parser_Ctx_struct * ctx);

     V4Parser_variableDefinition_return
     (*variableDefinition)	(struct V4Parser_Ctx_struct * ctx);

     V4Parser_variableDeclaration_return
     (*variableDeclaration)	(struct V4Parser_Ctx_struct * ctx);

     V4Parser_ifStmt_return
     (*ifStmt)	(struct V4Parser_Ctx_struct * ctx);

     V4Parser_elsePart_return
     (*elsePart)	(struct V4Parser_Ctx_struct * ctx);

     V4Parser_loopStmt_return
     (*loopStmt)	(struct V4Parser_Ctx_struct * ctx);

     V4Parser_repeatStmt_return
     (*repeatStmt)	(struct V4Parser_Ctx_struct * ctx);

     V4Parser_repeatSuffix_return
     (*repeatSuffix)	(struct V4Parser_Ctx_struct * ctx);

     V4Parser_breakStmt_return
     (*breakStmt)	(struct V4Parser_Ctx_struct * ctx);

     V4Parser_expressionStmt_return
     (*expressionStmt)	(struct V4Parser_Ctx_struct * ctx);

     V4Parser_blockStmt_return
     (*blockStmt)	(struct V4Parser_Ctx_struct * ctx);

     V4Parser_blockStart_return
     (*blockStart)	(struct V4Parser_Ctx_struct * ctx);

     V4Parser_blockEnd_return
     (*blockEnd)	(struct V4Parser_Ctx_struct * ctx);

     V4Parser_statementList_return
     (*statementList)	(struct V4Parser_Ctx_struct * ctx);

     V4Parser_assignmentStmt_return
     (*assignmentStmt)	(struct V4Parser_Ctx_struct * ctx);

     V4Parser_returnStmt_return
     (*returnStmt)	(struct V4Parser_Ctx_struct * ctx);

     V4Parser_expr_return
     (*expr)	(struct V4Parser_Ctx_struct * ctx);

     V4Parser_binaryExpr_return
     (*binaryExpr)	(struct V4Parser_Ctx_struct * ctx);

     V4Parser_unaryExpr_return
     (*unaryExpr)	(struct V4Parser_Ctx_struct * ctx);

     V4Parser_call_return
     (*call)	(struct V4Parser_Ctx_struct * ctx);

     V4Parser_slice_return
     (*slice)	(struct V4Parser_Ctx_struct * ctx);

     V4Parser_braces_return
     (*braces)	(struct V4Parser_Ctx_struct * ctx);

     V4Parser_place_return
     (*place)	(struct V4Parser_Ctx_struct * ctx);

     V4Parser_bool_return
     (*bool)	(struct V4Parser_Ctx_struct * ctx);

     V4Parser_literal_return
     (*literal)	(struct V4Parser_Ctx_struct * ctx);

     V4Parser_ranges_return
     (*ranges)	(struct V4Parser_Ctx_struct * ctx);

     V4Parser_list_expr_return
     (*list_expr)	(struct V4Parser_Ctx_struct * ctx);

     V4Parser_list_range_return
     (*list_range)	(struct V4Parser_Ctx_struct * ctx);

     V4Parser_binOp_return
     (*binOp)	(struct V4Parser_Ctx_struct * ctx);

     V4Parser_unOp_return
     (*unOp)	(struct V4Parser_Ctx_struct * ctx);

     ANTLR3_BOOLEAN
     (*synpred19_V4)	(struct V4Parser_Ctx_struct * ctx);

     ANTLR3_BOOLEAN
     (*synpred22_V4)	(struct V4Parser_Ctx_struct * ctx);

     ANTLR3_BOOLEAN
     (*synpred23_V4)	(struct V4Parser_Ctx_struct * ctx);

     ANTLR3_BOOLEAN
     (*synpred24_V4)	(struct V4Parser_Ctx_struct * ctx);

     ANTLR3_BOOLEAN
     (*synpred25_V4)	(struct V4Parser_Ctx_struct * ctx);

     ANTLR3_BOOLEAN
     (*synpred34_V4)	(struct V4Parser_Ctx_struct * ctx);
    // Delegated rules

    const char * (*getGrammarFileName)();
    void            (*reset)  (struct V4Parser_Ctx_struct * ctx);
    void	    (*free)   (struct V4Parser_Ctx_struct * ctx);
/* @headerFile.members() */
pANTLR3_BASE_TREE_ADAPTOR	adaptor;
pANTLR3_VECTOR_FACTORY		vectors;
/* End @headerFile.members() */
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API pV4Parser V4ParserNew         (
pANTLR3_COMMON_TOKEN_STREAM
 instream);
ANTLR3_API pV4Parser V4ParserNewSSD      (
pANTLR3_COMMON_TOKEN_STREAM
 instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the 
parser
 will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif
#define EOF      -1
#define T__48      48
#define T__49      49
#define T__50      50
#define T__51      51
#define T__52      52
#define T__53      53
#define T__54      54
#define T__55      55
#define T__56      56
#define T__57      57
#define T__58      58
#define T__59      59
#define T__60      60
#define T__61      61
#define T__62      62
#define T__63      63
#define T__64      64
#define T__65      65
#define T__66      66
#define T__67      67
#define T__68      68
#define T__69      69
#define T__70      70
#define T__71      71
#define T__72      72
#define T__73      73
#define T__74      74
#define T__75      75
#define T__76      76
#define T__77      77
#define T__78      78
#define T__79      79
#define T__80      80
#define ARG      4
#define ARR_TYPE      5
#define BIN_OP      6
#define BITS      7
#define BLOCK      8
#define BOOL_T      9
#define BRACES      10
#define BREAK      11
#define BYTE_T      12
#define CALL      13
#define CHAR      14
#define CHAR_T      15
#define DEC      16
#define DIM      17
#define ELSE      18
#define EXPR      19
#define FALSE      20
#define FUNC_DEF      21
#define FUNC_SIG      22
#define HEX      23
#define IDENTIFIER      24
#define IF      25
#define INT_T      26
#define LIST_ARG      27
#define LIST_EXPR      28
#define LIST_RANGE      29
#define LONG_T      30
#define LOOP      31
#define PLACE_EXPR      32
#define RANGES      33
#define REPEAT      34
#define RETURN      35
#define SLICE      36
#define SOURCE      37
#define SOURCE_ITEM      38
#define STRING      39
#define STRING_T      40
#define TRUE      41
#define UINT_T      42
#define ULONG_T      43
#define UNARY_OP      44
#define VAR_DEC      45
#define VAR_DEF      46
#define WS      47
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for V4Parser
 * =============================================================================
 */
/** } */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
