/** \file
 *  This C header file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : T.g
 *     -                            On : 2024-09-13 12:44:49
 *     -                 for the lexer : TLexerLexer
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The lexer 
TLexer

has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 *
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef pTLexer, which is returned from a call to TLexerNew().
 *
 * As this is a generated lexer, it is unlikely you will call it 'manually'. However
 * the methods are provided anyway.
 *
 * The methods in pTLexer are  as follows:
 *
 *  - 
 void
      pTLexer->T__10(pTLexer)
 *  - 
 void
      pTLexer->T__11(pTLexer)
 *  - 
 void
      pTLexer->T__12(pTLexer)
 *  - 
 void
      pTLexer->T__13(pTLexer)
 *  - 
 void
      pTLexer->T__14(pTLexer)
 *  - 
 void
      pTLexer->T__15(pTLexer)
 *  - 
 void
      pTLexer->T__16(pTLexer)
 *  - 
 void
      pTLexer->T__17(pTLexer)
 *  - 
 void
      pTLexer->T__18(pTLexer)
 *  - 
 void
      pTLexer->T__19(pTLexer)
 *  - 
 void
      pTLexer->T__20(pTLexer)
 *  - 
 void
      pTLexer->T__21(pTLexer)
 *  - 
 void
      pTLexer->T__22(pTLexer)
 *  - 
 void
      pTLexer->T__23(pTLexer)
 *  - 
 void
      pTLexer->T__24(pTLexer)
 *  - 
 void
      pTLexer->T__25(pTLexer)
 *  - 
 void
      pTLexer->T__26(pTLexer)
 *  - 
 void
      pTLexer->T__27(pTLexer)
 *  - 
 void
      pTLexer->T__28(pTLexer)
 *  - 
 void
      pTLexer->T__29(pTLexer)
 *  - 
 void
      pTLexer->T__30(pTLexer)
 *  - 
 void
      pTLexer->T__31(pTLexer)
 *  - 
 void
      pTLexer->T__32(pTLexer)
 *  - 
 void
      pTLexer->T__33(pTLexer)
 *  - 
 void
      pTLexer->T__34(pTLexer)
 *  - 
 void
      pTLexer->T__35(pTLexer)
 *  - 
 void
      pTLexer->T__36(pTLexer)
 *  - 
 void
      pTLexer->T__37(pTLexer)
 *  - 
 void
      pTLexer->T__38(pTLexer)
 *  - 
 void
      pTLexer->T__39(pTLexer)
 *  - 
 void
      pTLexer->T__40(pTLexer)
 *  - 
 void
      pTLexer->BOOL(pTLexer)
 *  - 
 void
      pTLexer->IDENTIFIER(pTLexer)
 *  - 
 void
      pTLexer->STRING(pTLexer)
 *  - 
 void
      pTLexer->HEX(pTLexer)
 *  - 
 void
      pTLexer->BITS(pTLexer)
 *  - 
 void
      pTLexer->DEC(pTLexer)
 *  - 
 void
      pTLexer->Tokens(pTLexer)
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_TLexer_H
#define _TLexer_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */

#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct TLexer_Ctx_struct TLexer, * pTLexer;



#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif

/** Context tracking structure for 
TLexer

 */
struct TLexer_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_LEXER    pLexer;

     void
     (*mT__10)	(struct TLexer_Ctx_struct * ctx);

     void
     (*mT__11)	(struct TLexer_Ctx_struct * ctx);

     void
     (*mT__12)	(struct TLexer_Ctx_struct * ctx);

     void
     (*mT__13)	(struct TLexer_Ctx_struct * ctx);

     void
     (*mT__14)	(struct TLexer_Ctx_struct * ctx);

     void
     (*mT__15)	(struct TLexer_Ctx_struct * ctx);

     void
     (*mT__16)	(struct TLexer_Ctx_struct * ctx);

     void
     (*mT__17)	(struct TLexer_Ctx_struct * ctx);

     void
     (*mT__18)	(struct TLexer_Ctx_struct * ctx);

     void
     (*mT__19)	(struct TLexer_Ctx_struct * ctx);

     void
     (*mT__20)	(struct TLexer_Ctx_struct * ctx);

     void
     (*mT__21)	(struct TLexer_Ctx_struct * ctx);

     void
     (*mT__22)	(struct TLexer_Ctx_struct * ctx);

     void
     (*mT__23)	(struct TLexer_Ctx_struct * ctx);

     void
     (*mT__24)	(struct TLexer_Ctx_struct * ctx);

     void
     (*mT__25)	(struct TLexer_Ctx_struct * ctx);

     void
     (*mT__26)	(struct TLexer_Ctx_struct * ctx);

     void
     (*mT__27)	(struct TLexer_Ctx_struct * ctx);

     void
     (*mT__28)	(struct TLexer_Ctx_struct * ctx);

     void
     (*mT__29)	(struct TLexer_Ctx_struct * ctx);

     void
     (*mT__30)	(struct TLexer_Ctx_struct * ctx);

     void
     (*mT__31)	(struct TLexer_Ctx_struct * ctx);

     void
     (*mT__32)	(struct TLexer_Ctx_struct * ctx);

     void
     (*mT__33)	(struct TLexer_Ctx_struct * ctx);

     void
     (*mT__34)	(struct TLexer_Ctx_struct * ctx);

     void
     (*mT__35)	(struct TLexer_Ctx_struct * ctx);

     void
     (*mT__36)	(struct TLexer_Ctx_struct * ctx);

     void
     (*mT__37)	(struct TLexer_Ctx_struct * ctx);

     void
     (*mT__38)	(struct TLexer_Ctx_struct * ctx);

     void
     (*mT__39)	(struct TLexer_Ctx_struct * ctx);

     void
     (*mT__40)	(struct TLexer_Ctx_struct * ctx);

     void
     (*mBOOL)	(struct TLexer_Ctx_struct * ctx);

     void
     (*mIDENTIFIER)	(struct TLexer_Ctx_struct * ctx);

     void
     (*mSTRING)	(struct TLexer_Ctx_struct * ctx);

     void
     (*mHEX)	(struct TLexer_Ctx_struct * ctx);

     void
     (*mBITS)	(struct TLexer_Ctx_struct * ctx);

     void
     (*mDEC)	(struct TLexer_Ctx_struct * ctx);

     void
     (*mTokens)	(struct TLexer_Ctx_struct * ctx);
    const char * (*getGrammarFileName)();
    void            (*reset)  (struct TLexer_Ctx_struct * ctx);
    void	    (*free)   (struct TLexer_Ctx_struct * ctx);
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API pTLexer TLexerNew         (
pANTLR3_INPUT_STREAM
 instream);
ANTLR3_API pTLexer TLexerNewSSD      (
pANTLR3_INPUT_STREAM
 instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the 
lexer
 will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif
#define EOF      -1
#define T__10      10
#define T__11      11
#define T__12      12
#define T__13      13
#define T__14      14
#define T__15      15
#define T__16      16
#define T__17      17
#define T__18      18
#define T__19      19
#define T__20      20
#define T__21      21
#define T__22      22
#define T__23      23
#define T__24      24
#define T__25      25
#define T__26      26
#define T__27      27
#define T__28      28
#define T__29      29
#define T__30      30
#define T__31      31
#define T__32      32
#define T__33      33
#define T__34      34
#define T__35      35
#define T__36      36
#define T__37      37
#define T__38      38
#define T__39      39
#define T__40      40
#define BITS      4
#define BOOL      5
#define DEC      6
#define HEX      7
#define IDENTIFIER      8
#define STRING      9
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for TLexer
 * =============================================================================
 */
/** } */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
