/** \file
 *  This C header file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : ../src/Var4Prev.g
 *     -                            On : 2024-09-25 11:36:46
 *     -                 for the lexer : Var4PrevLexerLexer
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The lexer 
Var4PrevLexer

has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 *
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef pVar4PrevLexer, which is returned from a call to Var4PrevLexerNew().
 *
 * As this is a generated lexer, it is unlikely you will call it 'manually'. However
 * the methods are provided anyway.
 *
 * The methods in pVar4PrevLexer are  as follows:
 *
 *  - 
 void
      pVar4PrevLexer->T__52(pVar4PrevLexer)
 *  - 
 void
      pVar4PrevLexer->T__53(pVar4PrevLexer)
 *  - 
 void
      pVar4PrevLexer->T__54(pVar4PrevLexer)
 *  - 
 void
      pVar4PrevLexer->T__55(pVar4PrevLexer)
 *  - 
 void
      pVar4PrevLexer->T__56(pVar4PrevLexer)
 *  - 
 void
      pVar4PrevLexer->T__57(pVar4PrevLexer)
 *  - 
 void
      pVar4PrevLexer->T__58(pVar4PrevLexer)
 *  - 
 void
      pVar4PrevLexer->T__59(pVar4PrevLexer)
 *  - 
 void
      pVar4PrevLexer->T__60(pVar4PrevLexer)
 *  - 
 void
      pVar4PrevLexer->T__61(pVar4PrevLexer)
 *  - 
 void
      pVar4PrevLexer->T__62(pVar4PrevLexer)
 *  - 
 void
      pVar4PrevLexer->T__63(pVar4PrevLexer)
 *  - 
 void
      pVar4PrevLexer->T__64(pVar4PrevLexer)
 *  - 
 void
      pVar4PrevLexer->T__65(pVar4PrevLexer)
 *  - 
 void
      pVar4PrevLexer->T__66(pVar4PrevLexer)
 *  - 
 void
      pVar4PrevLexer->T__67(pVar4PrevLexer)
 *  - 
 void
      pVar4PrevLexer->T__68(pVar4PrevLexer)
 *  - 
 void
      pVar4PrevLexer->T__69(pVar4PrevLexer)
 *  - 
 void
      pVar4PrevLexer->T__70(pVar4PrevLexer)
 *  - 
 void
      pVar4PrevLexer->T__71(pVar4PrevLexer)
 *  - 
 void
      pVar4PrevLexer->T__72(pVar4PrevLexer)
 *  - 
 void
      pVar4PrevLexer->T__73(pVar4PrevLexer)
 *  - 
 void
      pVar4PrevLexer->T__74(pVar4PrevLexer)
 *  - 
 void
      pVar4PrevLexer->T__75(pVar4PrevLexer)
 *  - 
 void
      pVar4PrevLexer->T__76(pVar4PrevLexer)
 *  - 
 void
      pVar4PrevLexer->T__77(pVar4PrevLexer)
 *  - 
 void
      pVar4PrevLexer->T__78(pVar4PrevLexer)
 *  - 
 void
      pVar4PrevLexer->T__79(pVar4PrevLexer)
 *  - 
 void
      pVar4PrevLexer->T__80(pVar4PrevLexer)
 *  - 
 void
      pVar4PrevLexer->T__81(pVar4PrevLexer)
 *  - 
 void
      pVar4PrevLexer->T__82(pVar4PrevLexer)
 *  - 
 void
      pVar4PrevLexer->T__83(pVar4PrevLexer)
 *  - 
 void
      pVar4PrevLexer->T__84(pVar4PrevLexer)
 *  - 
 void
      pVar4PrevLexer->TRUE(pVar4PrevLexer)
 *  - 
 void
      pVar4PrevLexer->FALSE(pVar4PrevLexer)
 *  - 
 void
      pVar4PrevLexer->BYTE_T(pVar4PrevLexer)
 *  - 
 void
      pVar4PrevLexer->INT_T(pVar4PrevLexer)
 *  - 
 void
      pVar4PrevLexer->UINT_T(pVar4PrevLexer)
 *  - 
 void
      pVar4PrevLexer->LONG_T(pVar4PrevLexer)
 *  - 
 void
      pVar4PrevLexer->ULONG_T(pVar4PrevLexer)
 *  - 
 void
      pVar4PrevLexer->CHAR_T(pVar4PrevLexer)
 *  - 
 void
      pVar4PrevLexer->STRING_T(pVar4PrevLexer)
 *  - 
 void
      pVar4PrevLexer->BOOL_T(pVar4PrevLexer)
 *  - 
 void
      pVar4PrevLexer->IDENTIFIER(pVar4PrevLexer)
 *  - 
 void
      pVar4PrevLexer->STRING(pVar4PrevLexer)
 *  - 
 void
      pVar4PrevLexer->CHAR(pVar4PrevLexer)
 *  - 
 void
      pVar4PrevLexer->HEX(pVar4PrevLexer)
 *  - 
 void
      pVar4PrevLexer->BITS(pVar4PrevLexer)
 *  - 
 void
      pVar4PrevLexer->DEC(pVar4PrevLexer)
 *  - 
 void
      pVar4PrevLexer->WS(pVar4PrevLexer)
 *  - 
 void
      pVar4PrevLexer->Tokens(pVar4PrevLexer)
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_Var4PrevLexer_H
#define _Var4PrevLexer_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */

#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct Var4PrevLexer_Ctx_struct Var4PrevLexer, * pVar4PrevLexer;



#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif

/** Context tracking structure for 
Var4PrevLexer

 */
struct Var4PrevLexer_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_LEXER    pLexer;

     void
     (*mT__52)	(struct Var4PrevLexer_Ctx_struct * ctx);

     void
     (*mT__53)	(struct Var4PrevLexer_Ctx_struct * ctx);

     void
     (*mT__54)	(struct Var4PrevLexer_Ctx_struct * ctx);

     void
     (*mT__55)	(struct Var4PrevLexer_Ctx_struct * ctx);

     void
     (*mT__56)	(struct Var4PrevLexer_Ctx_struct * ctx);

     void
     (*mT__57)	(struct Var4PrevLexer_Ctx_struct * ctx);

     void
     (*mT__58)	(struct Var4PrevLexer_Ctx_struct * ctx);

     void
     (*mT__59)	(struct Var4PrevLexer_Ctx_struct * ctx);

     void
     (*mT__60)	(struct Var4PrevLexer_Ctx_struct * ctx);

     void
     (*mT__61)	(struct Var4PrevLexer_Ctx_struct * ctx);

     void
     (*mT__62)	(struct Var4PrevLexer_Ctx_struct * ctx);

     void
     (*mT__63)	(struct Var4PrevLexer_Ctx_struct * ctx);

     void
     (*mT__64)	(struct Var4PrevLexer_Ctx_struct * ctx);

     void
     (*mT__65)	(struct Var4PrevLexer_Ctx_struct * ctx);

     void
     (*mT__66)	(struct Var4PrevLexer_Ctx_struct * ctx);

     void
     (*mT__67)	(struct Var4PrevLexer_Ctx_struct * ctx);

     void
     (*mT__68)	(struct Var4PrevLexer_Ctx_struct * ctx);

     void
     (*mT__69)	(struct Var4PrevLexer_Ctx_struct * ctx);

     void
     (*mT__70)	(struct Var4PrevLexer_Ctx_struct * ctx);

     void
     (*mT__71)	(struct Var4PrevLexer_Ctx_struct * ctx);

     void
     (*mT__72)	(struct Var4PrevLexer_Ctx_struct * ctx);

     void
     (*mT__73)	(struct Var4PrevLexer_Ctx_struct * ctx);

     void
     (*mT__74)	(struct Var4PrevLexer_Ctx_struct * ctx);

     void
     (*mT__75)	(struct Var4PrevLexer_Ctx_struct * ctx);

     void
     (*mT__76)	(struct Var4PrevLexer_Ctx_struct * ctx);

     void
     (*mT__77)	(struct Var4PrevLexer_Ctx_struct * ctx);

     void
     (*mT__78)	(struct Var4PrevLexer_Ctx_struct * ctx);

     void
     (*mT__79)	(struct Var4PrevLexer_Ctx_struct * ctx);

     void
     (*mT__80)	(struct Var4PrevLexer_Ctx_struct * ctx);

     void
     (*mT__81)	(struct Var4PrevLexer_Ctx_struct * ctx);

     void
     (*mT__82)	(struct Var4PrevLexer_Ctx_struct * ctx);

     void
     (*mT__83)	(struct Var4PrevLexer_Ctx_struct * ctx);

     void
     (*mT__84)	(struct Var4PrevLexer_Ctx_struct * ctx);

     void
     (*mTRUE)	(struct Var4PrevLexer_Ctx_struct * ctx);

     void
     (*mFALSE)	(struct Var4PrevLexer_Ctx_struct * ctx);

     void
     (*mBYTE_T)	(struct Var4PrevLexer_Ctx_struct * ctx);

     void
     (*mINT_T)	(struct Var4PrevLexer_Ctx_struct * ctx);

     void
     (*mUINT_T)	(struct Var4PrevLexer_Ctx_struct * ctx);

     void
     (*mLONG_T)	(struct Var4PrevLexer_Ctx_struct * ctx);

     void
     (*mULONG_T)	(struct Var4PrevLexer_Ctx_struct * ctx);

     void
     (*mCHAR_T)	(struct Var4PrevLexer_Ctx_struct * ctx);

     void
     (*mSTRING_T)	(struct Var4PrevLexer_Ctx_struct * ctx);

     void
     (*mBOOL_T)	(struct Var4PrevLexer_Ctx_struct * ctx);

     void
     (*mIDENTIFIER)	(struct Var4PrevLexer_Ctx_struct * ctx);

     void
     (*mSTRING)	(struct Var4PrevLexer_Ctx_struct * ctx);

     void
     (*mCHAR)	(struct Var4PrevLexer_Ctx_struct * ctx);

     void
     (*mHEX)	(struct Var4PrevLexer_Ctx_struct * ctx);

     void
     (*mBITS)	(struct Var4PrevLexer_Ctx_struct * ctx);

     void
     (*mDEC)	(struct Var4PrevLexer_Ctx_struct * ctx);

     void
     (*mWS)	(struct Var4PrevLexer_Ctx_struct * ctx);

     void
     (*mTokens)	(struct Var4PrevLexer_Ctx_struct * ctx);
    const char * (*getGrammarFileName)();
    void            (*reset)  (struct Var4PrevLexer_Ctx_struct * ctx);
    void	    (*free)   (struct Var4PrevLexer_Ctx_struct * ctx);
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API pVar4PrevLexer Var4PrevLexerNew         (
pANTLR3_INPUT_STREAM
 instream);
ANTLR3_API pVar4PrevLexer Var4PrevLexerNewSSD      (
pANTLR3_INPUT_STREAM
 instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the 
lexer
 will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif
#define EOF      -1
#define T__52      52
#define T__53      53
#define T__54      54
#define T__55      55
#define T__56      56
#define T__57      57
#define T__58      58
#define T__59      59
#define T__60      60
#define T__61      61
#define T__62      62
#define T__63      63
#define T__64      64
#define T__65      65
#define T__66      66
#define T__67      67
#define T__68      68
#define T__69      69
#define T__70      70
#define T__71      71
#define T__72      72
#define T__73      73
#define T__74      74
#define T__75      75
#define T__76      76
#define T__77      77
#define T__78      78
#define T__79      79
#define T__80      80
#define T__81      81
#define T__82      82
#define T__83      83
#define T__84      84
#define ARG      4
#define ARRAY_TYPE      5
#define ASSIGNMENT_STATEMENT      6
#define BIN_OP      7
#define BITS      8
#define BLOCK_STATEMENT      9
#define BOOL_T      10
#define BRACES_EXPR      11
#define BREAK_STATEMENT      12
#define BYTE_T      13
#define CALL      14
#define CHAR      15
#define CHAR_T      16
#define DEC      17
#define EXPR      18
#define EXPRESSION_STATEMENT      19
#define FALSE      20
#define FUNC_DEF      21
#define FUNC_SIGNATURE      22
#define GREATER      23
#define HEX      24
#define IDENTIFIER      25
#define IF_STATEMENT      26
#define INT_T      27
#define LIST_ARG      28
#define LIST_EXPR      29
#define LIST_RANGE      30
#define LITERAL      31
#define LONG_T      32
#define LOOP_STATEMENT      33
#define MINUS      34
#define PLACE_EXPR      35
#define PLUS      36
#define RANGES      37
#define REPEAT_STATEMENT      38
#define RETURN_STATEMENT      39
#define SLICE      40
#define SOURCE      41
#define SOURCE_ITEM      42
#define STRING      43
#define STRING_T      44
#define TRUE      45
#define UINT_T      46
#define ULONG_T      47
#define UNARY_OP      48
#define VARIABLE_DECLARATION      49
#define VARIABLE_DEFINITION      50
#define WS      51
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for Var4PrevLexer
 * =============================================================================
 */
/** } */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
